"""empty message

Revision ID: d74ac820c303
Revises: 07f385c56dec
Create Date: 2024-03-18 20:15:03.065318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74ac820c303'
down_revision = '07f385c56dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['planet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet')

    # ### end Alembic commands ###
